[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "derpinns"
version = "0.1.0"
description = "PINNS for solving PDEs"

[tool.setuptools.packages.find]
where = ["src"]        
